// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOjJCjAEYyFtJUbTfIo_r9iWJaJBJ8y7c',
    appId: '1:709706643318:web:b57a21444a40e7f6e86c57',
    messagingSenderId: '709706643318',
    projectId: 'signin-example-cdc45',
    authDomain: 'signin-example-cdc45.firebaseapp.com',
    storageBucket: 'signin-example-cdc45.appspot.com',
    measurementId: 'G-NWCPTHPBPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqALfVwRSeDC7nWaILHJvFssiM6GHZExs',
    appId: '1:709706643318:android:13c5c83f4ab54912e86c57',
    messagingSenderId: '709706643318',
    projectId: 'signin-example-cdc45',
    storageBucket: 'signin-example-cdc45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVFm1VdG2Xc2qSh5pcNpA8eKiiGJNtgp0',
    appId: '1:709706643318:ios:febd8bd234bb1fbee86c57',
    messagingSenderId: '709706643318',
    projectId: 'signin-example-cdc45',
    storageBucket: 'signin-example-cdc45.appspot.com',
    androidClientId: '709706643318-988khjbharl0fhnpt75l9o8g3cpipeqv.apps.googleusercontent.com',
    iosClientId: '709706643318-48epp2r7ou5da5l1fk93jhimgb0frr7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSignupLogin',
  );
}
